import re
from .utils import is_probably_timestamp, normalize_whitespace

_SPEAKER_LABEL_RE = re.compile(
    r"^\s*(speaker|host|guest|agent|user|you|presenter)\s*\d*\s*[:\-]\s*",
    re.IGNORECASE,
)
_TIMESTAMP_INLINE_RE = re.compile(
    r"(\[?\(?(?:\d{1,2}:)?\d{1,2}:\d{2}(?:,\d{3})?\)?\]?)"
)
_METADATA_MARKERS = [
    re.compile(r"^\s*\[?(music|applause|laughter|silence|background noise)\]?\s*$", re.IGNORECASE),
    re.compile(r"^\s*generated by.*loom.*transcript.*$", re.IGNORECASE),
]

def _strip_speaker_labels(line: str) -> str:
    return _SPEAKER_LABEL_RE.sub("", line)

def _strip_timestamps(line: str) -> str:
    # Kill standalone timestamps or inline brackets
    if is_probably_timestamp(line.strip()):
        return ""
    return _TIMESTAMP_INLINE_RE.sub("", line)

def _is_only_metadata(line: str) -> bool:
    l = line.strip()
    for rx in _METADATA_MARKERS:
        if rx.match(l):
            return True
    return False

def clean_transcript(raw_text: str) -> str:
    """
    Remove timestamps, speaker labels, and non-speech metadata.
    Normalize whitespace and join into readable paragraphs.
    """
    if not raw_text:
        return ""

    # Split preserving lines, clean line-by-line
    cleaned_lines = []
    for line in raw_text.replace("\r\n", "\n").split("\n"):
        line = _strip_timestamps(line)
        if not line.strip():
            cleaned_lines.append("")  # keep paragraph separation
            continue

        line = _strip_speaker_labels(line).strip()

        if _is_only_metadata(line) or not line:
            continue

        # remove extra inner spaces
        line = re.sub(r"\s{2,}", " ", line)
        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines)
    text = normalize_whitespace(text)

    # Post-process: convert multiple newlines to paragraph spacing
    text = re.sub(r"\n{2,}", "\n\n", text).strip()
    return text